apps/fomosto
src/snuffling.py

Given that kiwi was properly installed but lacking dependency Cheetah or gmtpy it would fail only saying
the kiwi tools must be installed to use this feature
This is kind of confusing. Now, fomosto is a bit more explicit as it now says e.g.
fomosto: error: the kiwi tools must be installed to use this feature 
No module named gmtpy

Added extended error message to fomosto export abort

---

src/gui_util.py
src/pile.py

Creating and printing an empty pile caused this exception:
Traceback (most recent call last):
File "parallel_pile.py", line 13, in <module>
do_something_parallel('E', p)
File "parallel_pile.py", line 6, in do_something_parallel
print shared_pile
File "/usr/local/lib/python2.7/dist-packages/pyrocko/pile.py", line 1146, in __str__
s += 'timerange: %s - %s\n' % (util.time_to_str(self.tmin), util.time_to_str(self.tmax))
File "/usr/local/lib/python2.7/dist-packages/pyrocko/util.py", line 613, in time_to_str
t0 = math.floor(t)
TypeError: a float is required

pile: string of empty pile doesn't throw exception

---

src/pile_viewer.py
src/snuffler.py

The menu's reading/writing QFileDialogs were broken. The Qt Docs don't list the default enum. I therefore added a 'dummy enum': QFileDialog.DontUseSheet

bugfix + Load events ()

---

src/gf/seismosizer.py

It may be convenient to have stores on a USB drive. However, querying engine.get_store_ids() caused an exception which then caused e.g. the cake snuffling to crash on startup if that drive was not mounted.

seismosizer: add logger, warn if super_dir not available

---

src/trace.py

Falls dtype von yc numpy.int32 ist, lieferte die Division mit normfac ein array von Nullen. So, tut es das nicht.

trace: de-abbreviate division

---

src/fdsn/ws.py

Wichtig um z.B. GERES Daten zu bekommen

fdsn/ws: Add BGR fdsn link

---

src/marker_editor.py

Sort "Time" and "Label" columns in marker editor by string, everything else by double representation.

marker_editor: better string/float sorting

---

src/config.py
src/topo/dataset.py
src/topo/srtmgl3.py
src/util.py

Since recently, srtmgl3 is only accessible after having provided a username and password. 
One needs to create an account at https://urs.earthdata.nasa.gov/
These credentials can be filled in the pyrocko config file as follows:
earthdata_credentials: [someusername, somepassword]
Maybe one should make this a little more secure, though... Opinions?

fix Srtmgl3 (recently broken due to authentication)

---

src/evalresp_ext.c
src/trace.py

Please check. evalresp_ext line 90 assigned r = first but first was not used afterwards neither deallocated, so I replaced r with first.
Includes also some cleanup.

Fix memory leak in evalresp_ext

---

src/snuffler.py

replaces "findChildren" with list to which panels are appended at startup. Disadvantage: (I think that) panels have to be added using add_panel (I am uncertain, however, what may be the consequence when adding panels with addDockWidget without appending the widget to the list - haven't tested that case). Advantage: snuffler opens in 0.7 instead of 1.0 seconds (plus time to load data).

snuffler: optimized snuffler startup

---

src/fdsn/ws.py

INGV requires lower case booleans. Do other services require upper case? Tests are ok.

ws: lower boolean query arguments

---

src/parstack_ext.c
src/util_ext.c

clang complained that rindex is deprecated. Replaced it. There is one more, though:
src/util_ext.c:120:10: warning: implicit declaration of function 'timegm' is invalid in C99
[-Wimplicit-function-declaration]
*t = timegm(&tm);
was it supposed to be replaced by my_timegm?

fix compiler warnings

---

README.md
doc/source/index.rst
examples/README.md
maintenance/deploy-docs.sh
src/fomosto/poel.py
src/fomosto/psgrn_pscmp.py
src/fomosto/qseis.py
src/fomosto/qssp.py

Hello!
The DOI foundation [recommends SSL/TLS to link to their resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) ;-) Also, since your homepages supports that as well, I updated those URLs also.
Cheers :-)

Link DOIs to preferred resolver

---

CITATION.bib
README.md

Hello! This [`CITATION` file convention is suggested by the Software Sustainability Institute](https://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files). Just a quick way for people to import the citation data into their reference management workflow. Cheers :-)

Offer citation metadata also as BibTeX

---

examples/automap_example.py

Hi, I just saw that there are some unused dependencies (like util and orthodrome) in the automap example. Sorry, I should have seen that before committing it last time.

remove unused dependencies, improved style

---

src/apps/fomosto.py

If an outfile was specified always only the last extracted travel time entry was written, because previous ones were overwritten ...

BUGFIX fomosto tttextract --output

---

src/gf/seismosizer.py
test/test_gf_scenarios.py
test/test_gf_sources.py

Here the `RectangularSource` is based on `SourceWithDerivedMagnitude` and not anymore `DCSource`. The advantage is that it can now more strictly check that slip and magnitude are not both set, and properly calculate the magnitude of a source with constant slip set (if given a velocity model).
One issue with the current implementation is that the moment is not factored out any more (stacking must now be done repeatedly for sources only differing only in magnitude) - should not be a big problem in practice.
The proposed change may break some backward compatibility for code relying on `RectangularSource` being a subclass of `DCSource` and with code accessing the magnitude or moment property of the object directly. These must now be accessed with `get_magnitude(store, target)` and …

gf: cleanup RectangularSource for constant slip / constant moment density

---

src/gui/snuffling.py

Convenience option to apply main control filters in chopper before returning traces.

gui.snuffling: return chopped, filtered traces

---

src/client/fdsn.py

Updated service URLs for some data centers according to the IRIS [datacenters](https://service.iris.edu/irisws/fedcatalog/1/datacenters?format=html) endpoint.
Also corrected the URL address for "ethz" data center, added "NIEP, Romania" data center, and deleted duplicate key for BGR.

fdsn: Updated service URLs for datacenters

---

src/gf/seismosizer.py
test/test_gf_sources.py

The moment of the discretized explosion source was too high. 
Added tests to cover this.

BUG: Fix explosion source

---

doc/source/apps/cake/manual.rst

Some parts of the rst-files still contain explicit codes
which can be replaced by linking them to the existing .py-file in the pyrocko archive (so done here for the cake-manual)

replacing explicit code with link

---

src/scenario/scenario.py
src/scenario/targets/base.py
src/scenario/targets/gnss_campaign.py
src/scenario/targets/insar.py
src/scenario/targets/waveform.py

Good evening,
It's often handy to have phase markers at hand, also when working with synthetic data. Adding tabulated phases now generates a `markers.txt` file on the fly for the `WaveformGenerator` for all station-source-combinations (given that the underlying earthmodel provides that phase):
tabulated_phases:
- !pf.TPDef
id: S
definition: 'stored:S'
- !pf.TPDef
id: p
definition: 'cake:p'

Scenario phases
