apps/fomosto

added this option
fomosto modelview --parameters vpvsratio
which displays the vp/vs ratio.

fomosto: added vp/vs ratio plot option modelview

---

src/gf/seismosizer.py

some convenience method that I could make use of

seismosizer: added from_pyrocko_trace method

---

doc/fomosto.rst

This might be helpful for others

fomosto docs: extended fomosto example

---

doc/fomosto.rst
src/trace.py

fomosto.rst: added fomosto computation code links

---

src/snufflings/ampspec.py

New documentation incl. reference of smoothing which can be applied to the spectra. Some layout improvements.

Ampspec overhaul 

---

src/gui_util.py
src/pile_viewer.py

This solves the bug that caused changing colors of event markers

bugfix: changing marker colors

---

src/moment_tensor.py
test/test_moment_tensor.py

Getter and setter methods for MomentTensor class

---

doc/snuffler_tutorial.rst
src/data/snuffler_help.html

snuffler_tutorial: Hint on the marker menu.

---

src/pile_viewer.py

This solves the problem of unsorted snufflings (except for birne, for some reasons I don't understand).

pile_viewer: sort snufflings by text()

---

apps/cake

cake: default P phase

---

apps/jackseis
src/trace.py
src/util.py

%j bei jackseis --output setzt den julianischen Tag nach dem 1. Januar.

julian day of year

---

setup.py

check if some version of xcode is available.

Osx setup fix

---

src/cake.py
src/gf/meta.py
src/gf/seismosizer.py

Deprecates the earlier slip_source PR ...

Slip source v2

---

src/gf/seismosizer.py

added detailed docstring to anchor point in stf

---

src/gf/seismosizer.py

finally all good things are 3 ;)

correct floating int's resolve numpy warning

---

src/gf/seismosizer.py
src/gf/store.py

fix for stacking stats problem

Stacking stats

---

src/marker_editor.py
src/pile_viewer.py

Useful feature, e.g. when snuffling and classifying lassie detections.

Show marker kinds in marker menu

---

doc/snuffler_tutorial.rst
src/config.py
src/gui_util.py
src/pile_viewer.py

Replaces #130 
I created this new PR after rebasing to master and adding some small modifications.

Snuffler config, v2

---

src/pile.py
src/trace.py
test/test_trace.py

allow traces to be pickled

---

src/gui_util.py
src/snuffling.py
src/util.py

Creates snuffler tabs with VTK renderers.
Within a snuffling, setting up a frame, adding VTKActors and initialization could look e.g. like this: 
[...]
frame = self.vtk_frame()
frame.add_actor(my_actor)
frame.init()

Snufflings' VTK integration

---

src/marker_editor.py
src/pile_viewer.py

Improves selection performance a lot when handling several thousands of markers

emit chunk-wise selection of markers to editor

---

src/ahfullgreen.py
src/ahfullgreen_ext.c
src/fomosto/ahfullgreen.py
test/test_ahfull.py
test/test_all.py
test/test_gf_qseis.py

@HerrMuellerluedenscheid are you ok with this? Some interfaces changed, so please check...

ahfullgreen: corrected, improved, restructured

---

doc/apps_cake_manual.rst
doc/apps_snuffler_manual.rst
doc/apps_snuffler_tutorial.rst
doc/install_details.rst
src/io.py
src/trace.py

Documentation: proof-reading

---

src/fomosto/psgrn_pscmp.py
test/test_gf_psgrn_pscmp.py

that little thing took me 2hrs ... just to mention too slow for the world again ...

included sample rate from fomosto config into traces and setup

---

src/gf/seismosizer.py

guts doesnt throw error anymore ...

convert to float

---

src/fdsn/station.py
test/test_fdsn.py

fdsn.station: from_pyrocko_stations

---

src/quakeml.py

add quakeml.py

---

src/gf/seismosizer.py

Happened to me now the thousands time and it hangs for ages, because it loops to find the stores and if your path is very long ...
I was wondering wth? Simply because the superdir was no list ...!
Added this list_check ...makes debugging easier ...

Engine input store superdir check

---

examples/automap_example.py

Added loading events from catalog file.

improved automap example

---

src/dataset/gshhg.py
test/test_gshhg.py

fix big evil bug in polygon coords

---

src/trace.py

Fixed error on no detections within seach window

---

src/fomosto/qseis.py
src/fomosto/qseis2d.py
src/fomosto/qssp.py
src/gf/builder.py
src/gf/store.py
src/spit.py

rebased, improved version of  #204 
solves #228

Fomosto check rebase

---

src/plot/beachball.py
test/test_beachball.py

Function for plotting a fuzzy beachball (beachball with uncertainties)
With and without best fit solution

plot.beachball: added fuzzy beachball

---

src/gf/server.py

Added JSON API to the server.
Added serving GF's velocity profiles through `cake_plot.my_model_plot`

GF Server JSON API

---

src/gf/seismosizer.py
src/gf/targets.py

also added docu warning about accuracy to the target quantity

request quantitiy velocity gives num.diff of displacement

---

setup.py
src/gf/ext/Makefile
src/gf/ext/eval_sinlookup.py
src/gf/ext/lut.c
src/gf/ext/lut.h
src/gf/ext/sinlookup.c
src/gf/ext/store_ext.c
src/gf/seismosizer.py
src/gf/store.py
test/test_gf_static.py

PR fixes excessive memory usage and improves performance.
new function `calc_statics` includes `make_sum_params` to avoid large matrices and better leverages OpenMP parallelisation.

GFStore Improved Static Summation

---

CHANGELOG.md
CONTRIBUTING.md
doc/source/apps/fomosto/tutorial.rst

Added changelog and contributing markdown files.

changelog and contributing 
